robot_base_frame: $(arg prefix)base_footprint
obstacle_range: 2.5
transform_tolerance: 0.4
update_frequency: 10.0
publish_frequency: 5.0
obstacle_range: 3.0
raytrace_range: 3.5
map_type: costmap
#mark_threshold: 1
publish_voxel_map: true
navigation_map:
  enable: true
  
obstacles:
  observation_sources: scan_marking scan_clearing rs_left_marking rs_left_clearing rs_right_marking rs_right_clearing
  scan_marking: {
    topic: scan_filtered,
    data_type: LaserScan,
    clearing: false,
    marking: true,
    observation_persistence: 0.5, 
    expected_update_rate: 0.5,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0
    }
  scan_clearing: {
    topic: scan_filtered,
    data_type: LaserScan,
    clearing: true,
    marking: false,
    observation_persistence: 0.5, 
    expected_update_rate: 0.5,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0,
    }
  rs_left_marking: {
    topic: rs_left_scan,
    data_type: LaserScan,
    clearing: false,
    marking: true,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0
    }
  rs_left_clearing: {
    topic: rs_left_scan,
    data_type: LaserScan,
    clearing: true,
    marking: false,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0,
    }
  rs_right_marking: {
    topic: rs_right_scan,
    data_type: LaserScan,
    clearing: false,
    marking: true,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0
    }
  rs_right_clearing: {
    topic: rs_right_scan,
    data_type: LaserScan,
    clearing: true,
    marking: false,
    observation_persistence: 0.0, 
    expected_update_rate: 0.0,
    inf_is_valid: false,
    min_obstacle_height: -0.5,
    max_obstacle_height: 1.0,
    }
virtual_walls_map:
  map_topic: maps/wall
  use_maximum: true
